# Generated by Django 4.0.3 on 2022-03-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_email_verfified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verify_code',
            field=models.CharField(default='12345', max_length=5),
            preserve_default=False,
        ),
    ]
