# Generated by Django 4.0.3 on 2022-03-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_email_verfified',
            field=models.IntegerField(default=0),
        ),
    ]
