# Generated by Django 4.0.3 on 2022-03-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_is_email_verfified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_email_verfified',
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.CharField(default='2', max_length=1),
        ),
    ]
