# Generated by Django 4.0.3 on 2022-03-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_profile_verify_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='two_step_verify_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twostep',
            field=models.BooleanField(default=False),
        ),
    ]
