# Generated by Django 4.0.3 on 2022-03-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_remove_classroom_club_classroom_book_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='book_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
