# Generated by Django 4.0.3 on 2022-03-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_clubmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='answer',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
